services:
  postgres:
    image: postgres:16
    container_name: artesanias_postgres
    restart: always
    environment:
      POSTGRES_USER: artesanias_user
      POSTGRES_PASSWORD: artesanias_pass
      POSTGRES_DB: artesanias_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: